name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # ✅ Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    # ✅ Copy env
    - name: Copy .env.example to .env
      run: cp ./.env.example ./.env

    # ✅ Install Node.js dependencies
    - name: Install dependencies
      run: npm ci

    # ✅ Make script executable
    - name: Make integration script executable
      run: chmod +x ./scripts/run-integration.sh

    # ✅ Run integration script
    - name: Run integration script
      run: ./scripts/run-integration.sh
